version: '3.9'

services:
  postgres:
    container_name: slackgpt_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slackgpt
    ports:
      - '5432:5432'
  redis:
    container_name: slackgpt_redis
    image: redis
    ports:
      - '6379:6379'
